# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-31 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_img', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='status',
            field=models.CharField(choices=[('scheduler', 'Scheduler'), ('ready', 'Ready')], default='scheduler', max_length=100),
        ),
    ]
