# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-31 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_img', '0002_auto_20160831_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchresult',
            name='rank',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='tag',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('ready', 'Ready')], default='scheduled', max_length=100),
        ),
    ]
