# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-05 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_img', '0003_auto_20160831_1905'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='status',
            new_name='status_google',
        ),
        migrations.AddField(
            model_name='tag',
            name='status_instagram',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('ready', 'Ready')], default='scheduled', max_length=100),
        ),
        migrations.AddField(
            model_name='tag',
            name='status_yandex',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('ready', 'Ready')], default='scheduled', max_length=100),
        ),
    ]
